# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kakaoFirebase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 #for Firebase login
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
 pod 'Firebase/Analytics'

pod 'FirebaseUI/Auth'
pod 'FirebaseUI/Google'
pod 'FirebaseUI/Facebook'

pod 'Firebase/Database'
pod 'CodableFirebase'
pod 'FMDB'

#for getJWT TOKEN from Firebase Functions
pod 'Alamofire','~> 5.0.0-rc.3'
pod 'Firebase/Functions'
pod 'NMapsMap' 
pod 'GoogleMaps'
pod 'GooglePlaces' 
pod 'Eureka'
pod 'Firebase/Storage'
pod 'Kingfisher', '~> 5.0'
pod 'MessageKit', :git => 'https://github.com/MessageKit/MessageKit.git', :branch => '3.0.0-swift5'
pod 'FirebaseFirestore'
pod 'SwiftyGif'



  # Pods for kakaoFirebase
  # Pods for FirebaseChat

end
